### ISSUE TITLE
nncompress doesn't work on chainer 6.5.0

### ISSUE THREAD

**Issue by KHiyowa** [chainer/models#39]
Hi,

"nncompress" doesn't work on chainer 6.5.0

in complessor/subfuncs.py,
def save_non_embed_npz(file, obj, compression=True):

Type of "obj" expected "complessor.net.EmbeddingCompressor", but "dict" on chainer 6.5.0 .
So I confront an error "AttributeError: 'dict' object has no attribute 'serialize'".

**Comment by soskek** [comment]
Thank you for feedback! I made and merged PR to fix it.
